### PR TITLE
Update MPU9250.h

### PR DESCRIPTION
**Pull request by BennehBoy**
Changed WHO_AM_I_AK8963  from 0x49 to 0x00 - otherwise initialisation fails

### CODE REVIEW

**Comment by mivoel** [comment]
Spent a good 30 min figuring this out myself. Hopefully this can be fixed soon. 

As per the [register map](https://cdn.sparkfun.com/assets/learn_tutorials/5/5/0/MPU-9250-Register-Map.pdf) WIA register for the AK8963 should be set to 0x00.

This is fixed in [this repo](https://github.com/sparkfun/MPU-9250_Breakout/blob/master/Libraries/Arduino/src/MPU9250.h). Perhaps both could be merged?

**Comment by moderndevice** [comment]
Also spent 30 minutes figuring this out - fix this line should be 0x00

#define WHO_AM_I_AK8963 0x49 // (AKA WIA) should return 0x48

Magnetometer is still broken though - wild yaw numbers on output.

**Review by jfrankert — APPROVED** [review]

**Comment by jfrankert** [comment]
I have confirmed the register update allows the code to run properly (I2C).

**Comment by tlf30** [comment]
A friend and I just spent 3 hours trouble shooting this, and found this answer. It is very disappointing that sparkfun does not even check to see if their code works. It is more disappointing that this pull request has not been merged.

**Comment by aster94** [comment]
Leave this library, i spent too muchhours here too, then i discovered that they never took the datasheet....
Google bolderflight mpu9250 spi and you will find a really good made lib

**Comment by Imantha123** [comment]
>Hi..I'm using the Arduino DUE and the MPU 9250. I have made the following
 connections with pull up using 10k resisters. After that i upload
MPU9250BasicAHRS_I2C example file for get the yaw pitch and roll.

VCC---3.3V
 GND---GND
 SCL---SCL21
SDA---SDA20

but in my serial monitor does not read the data. How can i get a pyr angles?
 could you please help me to get the pitch roll and yaw values.
 Thank you

**Pull request merged**
